/*
 * Copyright (c) Terl Tech Ltd • 08/05/18 22:59 • goterl.com
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/.
 */

package com.goterl.lazycode.lazysodium.interfaces;


import com.goterl.lazycode.lazysodium.exceptions.SodiumException;
import com.goterl.lazycode.lazysodium.utils.BaseChecker;
import com.goterl.lazycode.lazysodium.utils.Key;
import com.sun.jna.NativeLong;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

public interface Auth {

    int HMACSHA512256_BYTES = 32,
        HMACSHA512256_KEYBYTES = 32,
        HMACSHA256_BYTES = 32,
        HMACSHA256_KEYBYTES = 32,
        HMACSHA512_BYTES = 64,
        HMACSHA512_KEYBYTES = 32,

        BYTES = HMACSHA512256_BYTES,
        KEYBYTES = HMACSHA512256_KEYBYTES;


    class Checker extends BaseChecker {

    }

    interface Native {

        /**
         * Generate an authentication key.
         * @param k Auth key of size {@link #KEYBYTES}.
         */
        void cryptoAuthKeygen(byte[] k);

        /**
         * Computes a tag for the message in, whose length is inLen bytes, and the key k.
         * @param tag Tag of size {@link #BYTES}.
         * @param in A message.
         * @param inLen Message size.
         * @param key The key as generated by {@link #cryptoAuthKeygen(byte[])}.
         * @return True if successful.
         */
        boolean cryptoAuth(byte[] tag, byte[] in, long inLen, byte[] key);

        /**
         * Verifies that the tag stored at h is a
         * valid tag for the message in whose length
         * is inLen bytes, and the key k.
         * @param tag The tag.
         * @param in The message.
         * @param inLen Message bytes.
         * @param key The key as generated by {@link #cryptoAuthKeygen(byte[])}.
         * @return True if successful verification.
         */
        boolean cryptoAuthVerify(byte[] tag, byte[] in, long inLen, byte[] key);

    }

    interface Lazy {


    }

    enum Type {
        SHA256,
        SHA512,
        SHA512256
    }

    class StateHMAC256 extends Structure {
        public Hash.State256 ictx;
        public Hash.State256 octx;

        public static class ByReference extends StateHMAC256 implements Structure.ByReference { }

        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("ictx", "octx");
        }
    }

    class StateHMAC512 extends Structure {
        public Hash.State512 ictx;
        public Hash.State512 octx;

        public static class ByReference extends StateHMAC512 implements Structure.ByReference { }

        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("ictx", "octx");
        }
    }

    class StateHMAC512256 extends Structure {
        public Hash.State512 ictx;
        public Hash.State512 octx;

        public static class ByReference extends StateHMAC512256 implements Structure.ByReference { }

        @Override
        protected List<String> getFieldOrder() {
            return Arrays.asList("ictx", "octx");
        }
    }


}
