/*
 * Copyright (c) Terl Tech Ltd • 18/05/18 21:45 • goterl.com
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/.
 */

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import com.goterl.lazycode.lazysodium.exceptions.SodiumException;
import com.goterl.lazycode.lazysodium.interfaces.Hash;
import junit.framework.TestCase;
import org.junit.Test;

public class HashAndroidTest extends BaseTest {


    private String M1 = "With great power ";
    private String M2 = "comes great responsibility";
    private String MESSAGE = M1 + M2;

    @Test
    public void sha256Compare() throws SodiumException {
        String hashed1 = lazySodium.cryptoHashSha256(MESSAGE);
        String hashed2 = lazySodium.cryptoHashSha256(MESSAGE);
        TestCase.assertNotSame(hashed1, hashed2);
    }


    @Test
    public void multipartSha256() throws SodiumException {
        Hash.State256 state = new Hash.State256.ByReference();
        lazySodium.cryptoHashSha256Init(state);

        lazySodium.cryptoHashSha256Update(state, M1);
        lazySodium.cryptoHashSha256Update(state, M2);
        lazySodium.cryptoHashSha256Update(state, "more text to be hashed");

        String hash = lazySodium.cryptoHashSha256Final(state);
        TestCase.assertNotNull(hash);
    }

}
